server.port=8888
spring.application.name=bookstore
spring.main.web-application-type=none
spring.ai.mcp.server.name=bookstore-mcp
spring.ai.mcp.server.version=0.0.1

spring.main.banner-mode=off
logging.pattern.console=

spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always

spring.sql.init.data-locations=classpath:import.sql

# Control execution order
spring.jpa.defer-datasource-initialization=true