
langchain4j.open-ai.api-key=${OPENAI_API_KEY}

# Allowed models list
langchain4j.open-ai.chat-model.allowed-models=gpt-4,gpt-4o,gpt-4o-mini,o1-preview,o1-mini,gpt-4-turbo,gpt-3.5-turbo,gpt-4.5-preview

# Default model
langchain4j.open-ai.chat-model.model-name=gpt-4.5-preview
langchain4j.open-ai.chat-model.temperature=0.7
langchain4j.open-ai.chat-model.top-p=1.0
langchain4j.open-ai.chat-model.timeout=PT60S
langchain4j.open-ai.chat-model.max-tokens=1000
langchain4j.open-ai.chat-model.frequency-penalty=2
langchain4j.open-ai.chat-model.log-requests=false
langchain4j.open-ai.chat-model.log-responses=false
