# Common Model Configuration
langchain4j.chat-model.temperature=0.7
langchain4j.chat-model.top-p=1.0
langchain4j.chat-model.timeout=PT60S
langchain4j.chat-model.max-tokens=2000
langchain4j.chat-model.allowed-models=gpt-3.5-turbo, gpt-4, gpt-4-turbo, gpt-4o, gpt-4o-mini, gpt-5, gpt-5-mini, gpt-5-nano, o1-preview, o1-mini, claude-3-opus-latest, claude-3-7-sonnet-latest, claude-3-5-haiku-latest, gemini-2.0-flash, gemini-2.0-flash-lite, gemini-1.5-pro, mistral-small-latest, pixtral-12b-2409, open-mistral-nemo, llama3.2, deepseek-r1:32b
langchain4j.chat-model.frequency-penalty=0.0
langchain4j.chat-model.log-requests=true
langchain4j.chat-model.log-responses=true

# OpenAI Configuration
langchain4j.open-ai.api-key=${OPENAI_API_KEY}
langchain4j.open-ai.organization-id=${OPENAI_ORG_ID:NONE}
langchain4j.open-ai.base-url=https://api.openai.com/v1
langchain4j.open-ai.chat-model.model-name=gpt-5

# Anthropic Configuration
langchain4j.anthropic.api-key=${ANTHROPIC_API_KEY}
langchain4j.anthropic.base-url=https://api.anthropic.com
langchain4j.anthropic.version=2024-02-29
langchain4j.anthropic.chat-model.model-name=claude-3-opus-latest

# Google Configuration
langchain4j.google.api-key=${GOOGLE_API_KEY}
langchain4j.google.base-url=https://generativelanguage.googleapis.com/v1beta/openai/
langchain4j.google.chat-model.model-name=gemini-2.0-flash

# Mistral Configuration
langchain4j.mistral.api-key=${MISTRAL_API_KEY}
langchain4j.mistral.base-url=https://api.mistral.ai/v1
langchain4j.mistral.safe-mode=true
langchain4j.mistral.chat-model.model-name=mistral-small-latest

# Default Personality Type
langchain4j.personality-type=JAVA_CHAMPION
